#include <Arduino.h>
#include "BlePaddleKeyboard.h"
#include "PaddleDebug.h"
#include "StatusLed.h"
#include "PaddleRouter.h"

#if ARDUINO_USB_CDC_ON_BOOT || ARDUINO_USB_MODE != 0
#error "Select USB-OTG (TinyUSB), USB CDC On Boot Disabled"
#endif

namespace {
constexpr uint8_t ditPin = 4;
constexpr uint8_t dahPin = 5;
bool statusLogged = false;
MorseBle::Status lastStatus = MorseBle::Status::Waiting;
StatusLed statusLed;
MorseBridge::PaddleRouter router;
#if MORSEBRIDGE_DEBUG
PaddleDebug paddleDebug;
#endif

void logStatus() {
  const auto status = router.status();
  statusLed.update(status, millis());
  if (statusLogged && status == lastStatus) return;
  statusLogged = true;
  lastStatus = status;
  switch (status) {
    case MorseBle::Status::Waiting:
      PaddleLog::println("Status: waiting; connect USB data cable or pair with MorseBridge");
      break;
    case MorseBle::Status::Connecting:
      PaddleLog::println("Status: waiting for HID subscription, route release, or USB resume");
      break;
    case MorseBle::Status::ReleasePaddles:
      PaddleLog::println("Status: release BOTH paddles to arm");
      break;
    case MorseBle::Status::Ready:
      PaddleLog::println("Status: BLE ready; timing and sidetone are generated by Morse-it");
      break;
    case MorseBle::Status::UsbReady:
      PaddleLog::println("Status: USB ready; Bluetooth paddle reports suppressed");
      break;
    case MorseBle::Status::Error:
      PaddleLog::println("Status: ERROR; inspect USB/BLE messages, then reset/power-cycle");
      break;
  }
}
}

void setup() {
  pinMode(ditPin, INPUT_PULLUP);
  pinMode(dahPin, INPUT_PULLUP);
  DebugSerial.begin(115200);
  MorseUsb::begin();
  statusLed.begin();
  statusLed.update(MorseBle::Status::Waiting, millis());
  PaddleLog::println("MorseBridge: Waveshare ESP32-S3-Zero; USB + BLE HID, USB priority");
  PaddleLog::println("Inputs: dit GPIO4, dah GPIO5, active LOW; debounce 5 ms");
  MorseBle::begin();
  router.update(false, false);
  logStatus();
}

void loop() {
  const bool ditDown = digitalRead(ditPin) == LOW;
  const bool dahDown = digitalRead(dahPin) == LOW;
  router.update(ditDown, dahDown);
  logStatus();
  PaddleLog::poll();
#if MORSEBRIDGE_DEBUG
  paddleDebug.sample(ditDown, dahDown, millis(), MorseBle::diagnostics(),
                     MorseUsb::diagnostics(), router.route());
#endif
  delay(1);
}
