#include <Arduino.h>
#include "BlePaddleKeyboard.h"
#include "PaddleDebug.h"
#include "StatusLed.h"

#if !ARDUINO_USB_CDC_ON_BOOT || ARDUINO_USB_MODE != 1
#error "Enable USB CDC On Boot and select Hardware CDC and JTAG"
#endif

namespace {
constexpr uint8_t ditPin = 4;
constexpr uint8_t dahPin = 5;
bool startupFailed = false;
bool statusLogged = false;
MorseBle::Status lastStatus = MorseBle::Status::Waiting;
StatusLed statusLed;
#if MORSEBRIDGE_DEBUG
PaddleDebug paddleDebug;
#endif

void logStatus() {
  const auto status = startupFailed ? MorseBle::Status::Error : MorseBle::status();
  statusLed.update(status, millis());
  if (statusLogged && status == lastStatus) return;
  statusLogged = true;
  lastStatus = status;
  switch (status) {
    case MorseBle::Status::Waiting:
      PaddleLog::println("Status: waiting for iPhone; pair with MorseBridge");
      break;
    case MorseBle::Status::Connecting:
      PaddleLog::println("Status: connected, waiting for HID subscription or resume");
      break;
    case MorseBle::Status::ReleasePaddles:
      PaddleLog::println("Status: release BOTH paddles to arm");
      break;
    case MorseBle::Status::Ready:
      PaddleLog::println("Status: ready; timing and sidetone are generated by Morse-it");
      break;
    case MorseBle::Status::Error:
      PaddleLog::println("Status: ERROR; inspect BLE messages, then reset/power-cycle");
      break;
  }
}
}

void setup() {
  pinMode(ditPin, INPUT_PULLUP);
  pinMode(dahPin, INPUT_PULLUP);
  Serial.begin(115200);
  Serial.setTxTimeoutMs(0);  // No USB host is required; never wait for log delivery.
  statusLed.begin();
  statusLed.update(MorseBle::Status::Waiting, millis());
  PaddleLog::println("MorseBridge: Waveshare ESP32-S3-Zero; BLE HID only");
  PaddleLog::println("Inputs: dit GPIO4, dah GPIO5, active LOW; debounce 5 ms");
  startupFailed = !MorseBle::begin();
  logStatus();
}

void loop() {
  const bool ditDown = digitalRead(ditPin) == LOW;
  const bool dahDown = digitalRead(dahPin) == LOW;
  if (!startupFailed) {
    MorseBle::update(ditDown, dahDown);
  }
  logStatus();
  PaddleLog::poll();
#if MORSEBRIDGE_DEBUG
  paddleDebug.sample(ditDown, dahDown, millis(), MorseBle::diagnostics());
#endif
  delay(1);
}
